### ISSUE TITLE
Failed to connect to badges.twitch.tv/127.1.1.1:443

### ISSUE THREAD

**Issue by 32803** [flex3r/DankChat#126]
Since maybe a week ago i have started getting these errors every time i launch dankchat. Really love the app but not being able to see third party emotes or even badges next to peoples names kinda sucks. Using an S9 with Android 10, happens on every version of dankchat ive tried. Really cant think of anything i did that danked it up, just kinda happened one day. The errors it blurts out are cv pasted below ;)

java.net.ConnectException: Failed to connect to badges.twitch.tv/127.1.1.1:443
	at m.s0.g.j.e(:14)
	at m.s0.g.j.c(:14)
	at m.s0.g.d.a(:54)
	at m.s0.g.a.a(:11)
	at m.s0.h.g.b(:3)
	at m.s0.e.a.a(:152)
	at m.s0.h.g.b(:3)
	at m.s0.h.a.a(:17)
	at m.s0.h.g.b(:3)
	at m.s0.h.i.a(:26)
	at m.s0.h.g.b(:3)
	at e.a.a.z0.b.a(:21)
	at m.s0.h.g.b(:3)
	at m.s0.g.e.h(:12)
	at m.s0.g.e$a.run(:6)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.net.ConnectException: failed to connect to badges.twitch.tv/127.1.1.1 (port 443) from /127.0.0.1 (port 39474) after 10000ms: isConnected failed: ECONNREFUSED (Connection refused)
	at libcore.io.IoBridge.isConnected(IoBridge.java:288)
	at libcore.io.IoBridge.connectErrno(IoBridge.java:193)
	at libcore.io.IoBridge.connect(IoBridge.java:135)
	at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
	at java.net.Socket.connect(Socket.java:621)
	at m.s0.l.h.e(Unknown Source:10)
	at m.s0.g.j.e(:12)
	... 17 more
Caused by: android.system.ErrnoException: isConnected failed: ECONNREFUSED (Connection refused)
	at libcore.io.IoBridge.isConnected(IoBridge.java:275)
	... 27 more

**Comment by flex3r** [comment]
Do you have an adblocker or DNS filter running on your phone or in your network?  
This is definetly not an issue of dankchat since the badges endpoint works fine for me

**Comment by flex3r** [comment]
Closing this for now, feel free to reopen if you think this is an issue on the app's side :)
